@baseUrl = http://localhost:3000
@tokenUsuario = PEGAR_TOKEN_USUARIO
@tokenAdmin = PEGAR_TOKEN_ADMIN

### Principal
GET {{baseUrl}}

### Health
GET {{baseUrl}}/health

### Login usuario
POST {{baseUrl}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "ana@email.com",
  "password": "usuario123"
}

### Login admin
POST {{baseUrl}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "admin@email.com",
  "password": "admin123"
}

### Login incorrecto: 401
POST {{baseUrl}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "ana@email.com",
  "password": "incorrecta"
}

### Perfil sin token: 401
GET {{baseUrl}}/api/v1/usuarios/perfil

### Perfil con token: 200
GET {{baseUrl}}/api/v1/usuarios/perfil
Authorization: Bearer {{tokenUsuario}}

### Usuario común intenta listar usuarios: 403
GET {{baseUrl}}/api/v1/usuarios
Authorization: Bearer {{tokenUsuario}}

### Admin lista usuarios: 200
GET {{baseUrl}}/api/v1/usuarios
Authorization: Bearer {{tokenAdmin}}

### Token inválido: 401
GET {{baseUrl}}/api/v1/usuarios/perfil
Authorization: Bearer token-invalido
